# Generated by Django 5.2.5 on 2025-10-03 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
