# Generated by Django 5.2.5 on 2025-10-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
