# Generated by Django 5.2.5 on 2025-10-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_created',
        ),
    ]
