# Generated by Django 5.2.5 on 2025-10-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
