# Generated by Django 5.2.5 on 2025-09-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='durations',
            new_name='duration',
        ),
    ]
